### PR TITLE
Stop going into a death spiral when a provider disconnects

### LINKED ISSUE #86: Type assignment of root being cleared
This should be constant (and thus not cleared) and there is some code predicated on this assertion.

However on disconnecting a provider I got a load of "Attempted to taint parent of root" spam, which was unexpected.

### PR DESCRIPTION
**Pull request by foolswood**
Resolves #86.

### CODE REVIEW

File: src/Clapi/Valuespace.hs [hunk 1]
```diff
@@ -464,7 +464,7 @@ vsRelinquish ns (Valuespace tree defs tas xrefs) =
       (Tree.treeDelete nsp tree)
       (Map.delete ns defs)
       (Mos.filterDeps
-       (\p (TypeName ns' _) -> p `Path.isChildOf` nsp || ns == ns') tas)
+       (\p (TypeName ns' _) -> not $ p `Path.isChildOf` nsp || ns == ns') tas)
```
Comment (foolswood) [inline src/Clapi/Valuespace.hs]: Test for this.

File: src/Clapi/Valuespace.hs [hunk 2]
```diff
@@ -361,7 +361,7 @@ processToRelayProviderDigest trpd vs =
     unless (null updateErrs) $ Left $ Map.mapKeys PathError updateErrs
     (updatedTypes, vs') <- first (fmap $ fmap $ Text.pack . show) $ validateVs
       (Map.fromSet (const Nothing) redefdPaths <> updatedPaths) $
-      Valuespace tree' defs' (vsTyAssns vs) xrefs'
+      Valuespace tree' defs' tas xrefs'
```
Comment (foolswood) [inline src/Clapi/Valuespace.hs]: Test that checks the resulting tyAssns are right.

File: test/PathSpec.hs [hunk 3]
```diff
@@ -38,6 +38,11 @@ spec = do
         it "Empty path" $ rt "/"
         it "Top level path" $ rt "/fdoo"
         it "Nested path" $ rt "/boo_1/chew_2"
+    describe "isChildOf" $ do
+        it "Child -> True" $ isChildOf [pathq|/a/b/c/d|] [pathq|/a|] `shouldBe` True
```
Comment (ch3pjw) [inline test/PathSpec.hs]: Might be more canonical to write `[pathq|/a/b/c/d|] ``shouldSatisfy`` isChildOf [pathq|/a|]` and likewise with `shouldNotSatisfy`

File: src/Clapi/Valuespace.hs [hunk 4]
```diff
@@ -80,7 +80,7 @@ data Valuespace = Valuespace
   } deriving (Eq, Show)
 
 removeTamSubtree :: TypeAssignmentMap -> Path -> TypeAssignmentMap
-removeTamSubtree tam p = Mos.filterDependencies (`Path.isChildOf` p) tam
+removeTamSubtree tam p = Mos.filterDependencies (not . flip Path.isChildOf p) tam
```
Comment (ch3pjw) [inline src/Clapi/Valuespace.hs]: :+1: Woops, my bad! Thanks :-)

File: src/Data/Map/Mos.hs [hunk 5]
```diff
@@ -115,7 +115,7 @@ filterDeps f (deps, revDeps) =
   let
     (toKeep, toDrop) = Map.partitionWithKey f deps
   in
-    (toKeep, flip Set.difference (Map.keysSet toDrop) <$> revDeps)
+    (toKeep, Map.filter (not . null) $ flip Set.difference (Map.keysSet toDrop) <$> revDeps)
```
Comment (ch3pjw) [inline src/Data/Map/Mos.hs]: Is this basically a `Mos.dropItems` or something we could abstract out?

File: src/Clapi/Types/Digests.hs [hunk 6]
```diff
@@ -56,7 +56,7 @@ trpDigest :: Seg -> TrpDigest
 trpDigest ns = TrpDigest ns mempty alEmpty mempty mempty
 
 trpdRemovedPaths :: TrpDigest -> [Path]
-trpdRemovedPaths (TrpDigest _ _ _ cOps _) = Map.foldlWithKey f [] cOps
+trpdRemovedPaths (TrpDigest ns _ _ cOps _) = (ns :</) <$> Map.foldlWithKey f [] cOps
```
Comment (ch3pjw) [inline src/Clapi/Types/Digests.hs]: Was there a reason not to qualify them outside of this function? It's gone from being a kind of data projection function to doing some transformation...

Comment (foolswood) [reply src/Clapi/Types/Digests.hs]: I was thinking that since it took the whole digest in that it should take into account whatever information the digest contained so the caller didn't have to unpack it. If you want the other one then I think this should take the `ContainerOps` not the digest since that would make explicit that the caller will need to have unpacked the digest not to end up unqualified.
