### PR TITLE
Test and fix qualifying of data digest paths

### LINKED ISSUE #90: Provider data update not broadcast to subscribers
Trace below:
```
# Sub to transport state:
-> webgui TimeStamped (Time 94 609885356,Trcd (TrcDigest
    { TypeSubs = fromList []
    , DataSubs = fromList [(/engine/transport/state,OpSubscribe)]
    , Data = AssocList {unAssocList = []}
    , ContainerOps = fromList []
    }))
# Get initial subscription response from relay
<- webgui Frcd (FrcDigest
    { TypeUnsubs = fromList [], DataUnsubs = fromList []
    , Definitions = fromList [(engine:transport_state,OpDefine
        { odDef = TupleDef (TupleDefinition {tupDefDoc = "playhead", tupDefTypes = AssocList {unAssocList = [("state",TtConc (TcEnum ["transport_stopped","transport_rolling"]))]}, tupDefInterpLimit = ILUninterpolated})})]
    , TypeAssignments = fromList [(/engine/transport/state,(engine:transport_state,Must))]
    , Data = AssocList {unAssocList = [(/engine/transport/state,ConstChange Nothing [WireValue 0])]}
    , ContainerOps = fromList [], Errors = fromList []})

# Client initiates transport state change
-> webgui TimeStamped (Time 103 678604833,Trcd (TrcDigest
    { TypeSubs = fromList [], DataSubs = fromList []
    , Data = AssocList {unAssocList = [(/engine/transport/state,ConstChange (Just "someone") [WireValue 1])]}
    , ContainerOps = fromList []}))
# Weird empty bundle (see issue #87)
<- webgui Frcd (FrcDigest
    { TypeUnsubs = fromList [], DataUnsubs = fromList [], Definitions = fromList [], TypeAssignments = fromList []
    , Data = AssocList {unAssocList = []}, ContainerOps = fromList [], Errors = fromList []})
# Change forwarded to provider
<- engine Frpd (FrpDigest
    { Namespace = "engine"
    , Data = AssocList {unAssocList = [(/transport/state,ConstChange (Just "someone") [WireValue 1])]}
    , ContainerOps = fromList []})
# Provider accepts change resulting in state change
-> engine TimeStamped (Time 21303 3111078480,Trpd (TrpDigest
    { Namespace = "engine", Definitions = fromList []
    , Data = AssocList {unAssocList = [(/transport/state,ConstChange Nothing [WireValue 1]),(/transport/changed,ConstChange Nothing [WireValue (Time 21303 3110482034)])]}
    , ContainerOps = fromList [], Errors = fromList []}))

# ! Distinct lack of subscriber update
```

### PR DESCRIPTION
**Pull request by foolswood**
Resolves #90.

### CODE REVIEW

File: src/Clapi/Relay.hs [hunk 1]
```diff
@@ -124,27 +125,28 @@ relay vs = waitThenFwdOnly fwd
             nsContOp (StructDef (StructDefinition _ kids)) = Map.singleton ns
               (Nothing, SoPresentAfter $ presentAfter ns $ alKeys kids)
             nsContOp _ = error "Root def not a struct WTAF"
-            defs' = vsMinimiseDefinitions defs vs
-            dd' = vsMinimiseDataDigest dd vs
-            contOps' = vsMinimiseReords contOps vs
+            qDd = maybe (error "Bad sneakers") id $ alMapKeys (ns :</) dd
```
Comment (ch3pjw) [inline src/Clapi/Relay.hs]: "Bad sneakers"? Am I missing a reference?!

Comment (foolswood) [reply src/Clapi/Relay.hs]: It's a Steely Dan song, and I don't think it is an error I've used before.
